# Generated by Django 3.1.7 on 2021-02-21 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_quantiy', models.IntegerField()),
                ('product_brand', models.CharField(max_length=30)),
                ('product_added_on', models.DateField()),
                ('product_price', models.BigIntegerField()),
                ('product_is_avaliable', models.BooleanField()),
                ('product_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_on', models.DateField()),
                ('purchased_quantity', models.IntegerField()),
                ('product_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
