# Generated by Django 3.1.7 on 2021-02-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210222_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_added_on',
            field=models.DateField(auto_now=True),
        ),
    ]
